fix TypeError: cannot unpack non-iterable EventWorkspace object
- scaling_factors() was returning a workspace if the file could not be
  found. But that is not the contractual return set of the function.
- TODO: add guards to define the expected types returned
- TODO: scaling_factors as a function name is unfortunate choice due to
  the use of scaling_factors variables as scalar float...
- TODO: still have 3 (existing) test errors after this commit:

FAILED tests/integration/lr_reduction/test_reduction.py::test_q_summing - AssertionError: assert np.float64(0.00013047397930315922) < 1e-06
FAILED tests/integration/lr_reduction/test_reduction.py::test_full_reduction - FileNotFoundError: data/reference_rq.txt not found.
FAILED tests/integration/lr_reduction/test_reduction.py::test_reduce_workflow - assert np.float64(431.52279259987563) < 0.07